version: '3'

services:
  db:
    container_name: milan-gtfs-db
    image: postgres
    build: "./db"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_HOST: 'db'
      POSTGRES_DB: 'milan-gtfs'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'admin'

  db-admin:
    container_name: milan-gtfs-db-admin
    image: adminer
    depends_on:
    - db
    ports:
      - 8080:8080

volumes:
  db_data: {}